### ISSUE TITLE
Quick question about your License.

### ISSUE THREAD

**Issue by ben-xo** [cubiclesoft/php-discord-sdk#3]
Hi there! Super pleased to have found your project - just a tiny question about the license. The doc says "MIT or LGPL" - but each of the bundled files says All Right Reserved in the header. Is this by accident or is only some of the code under MIT/LGPL?

Many thanks, just want to make sure I'm staying on the right side of this.

(Hoping to use it to integrate https://github.com/ben-xo/sslscrobbler with Discord).

**Comment by cubiclesoft** [comment]
Short answer:  Pick MIT or LGPL and you are done.  (Most people pick MIT since it is the more liberal license.  But some people don't like mixing licenses and already use LGPL, so they pick LGPL for consistency.)

Longer answer:

The source code says All Rights Reserved as standard CubicleSoft practice.  The open source license options are adapted to the source code at publishing time.

If this were a commercial CubicleSoft product, the source code would not offer any open source licenses nor be on a public GitHub repository - a repo would likely be created for the sole purpose of tracking bugs, but no source code.  The software is used for both internal and external purposes.  The internal software (what you don't see) is privately licensed and owned entirely by CubicleSoft - e.g. clicking the Discord button on the repo's main page uses the PHP Discord SDK but the version I use is not open source.  The external software (what you see here on GitHub) is open source and the project can be used freely after selecting a license:  It just happens to be the same identical source code as the closed source version.  The headers of the source code aren't changed but the chosen open source license applies.  In this case, MIT or LGPL are offered as the two licensing options to choose from.  The critical difference is where the code originates from and the licenses that are offered.  Basically, I can use the same software in a larger closed source/commercial product and have the entire product be under a commercial license while also offering it separately as an open source product.  Hopefully that clarifies what's going on.

**Comment by ben-xo** [comment]
Yes, your licensing policy makes perfect sense. Thank you for taking the time to clarify.
